name: Gerar APK SuperGente

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permissao Executavel
        run: chmod +x gradlew

      - name: Compilar Projeto
        run: ./gradlew assembleDebug

      - name: Baixar APK
        uses: actions/upload-artifact@v4
        with:
          name: SuperGente-App
          path: "**/build/outputs/apk/debug/*.apk"
